name: Build Docs

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Build docs
        run: tools/export.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: build/
